"""Add similar image table

Revision ID: 0b1f4a1b36a0
Revises: 7bf42a6cc944
Create Date: 2018-07-30 12:23:44.723276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1f4a1b36a0'
down_revision = '7bf42a6cc944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similar_image',
        sa.Column('left_id', sa.Integer(), nullable=True),
        sa.Column('right_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['left_id'], ['image.id'], ),
        sa.ForeignKeyConstraint(['right_id'], ['image.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similar_image')
    # ### end Alembic commands ###
