"""Add extra data for galleries and images

Revision ID: 0fe7cf51bacc
Revises: 6119983db3b3
Create Date: 2018-07-12 14:16:04.562560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe7cf51bacc'
down_revision = '6119983db3b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gallery', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('gallery', sa.Column('name', sa.String(), nullable=True))
    op.add_column('gallery', sa.Column('year', sa.SmallInteger(), nullable=True))
    op.add_column('image', sa.Column('camera', sa.String(), nullable=True))
    op.add_column('image', sa.Column('datetime', sa.DateTime(), nullable=True))
    op.add_column('image', sa.Column('lens', sa.String(), nullable=True))
    op.add_column('image', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'location')
    op.drop_column('image', 'lens')
    op.drop_column('image', 'datetime')
    op.drop_column('image', 'camera')
    op.drop_column('gallery', 'year')
    op.drop_column('gallery', 'name')
    op.drop_column('gallery', 'date')
    # ### end Alembic commands ###
