"""Add image relation

Revision ID: 5628f67a9a63
Revises: 7bf42a6cc944
Create Date: 2018-08-14 12:34:56.376486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5628f67a9a63'
down_revision = '7bf42a6cc944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_to_image',
        sa.Column('left_id', sa.Integer(), nullable=False),
        sa.Column('right_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['left_id'], ['image.id'], ),
        sa.ForeignKeyConstraint(['right_id'], ['image.id'], ),
        sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_to_image')
    # ### end Alembic commands ###
