"""Add base tables

Revision ID: 6119983db3b3
Revises: 
Create Date: 2018-07-11 12:07:33.666035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6119983db3b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('path', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('path', sa.String(), nullable=True),
        sa.Column('phash', sa.String(), nullable=True),
        sa.Column('gallery_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['gallery_id'], ['gallery.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_table('gallery')
    # ### end Alembic commands ###
