"""Added descriptor table

Revision ID: 78654a971722
Revises: 0fe7cf51bacc
Create Date: 2018-07-19 09:17:02.742832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78654a971722'
down_revision = '0fe7cf51bacc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('descriptor',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('vector', sa.ARRAY(sa.Float()), nullable=True),
        sa.Column('image_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('descriptor')
    # ### end Alembic commands ###
