"""Add image dimensions

Revision ID: 7bf42a6cc944
Revises: 497e808991cc
Create Date: 2018-07-30 11:11:48.280349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf42a6cc944'
down_revision = '497e808991cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('image', sa.Column('width', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'width')
    op.drop_column('image', 'height')
    # ### end Alembic commands ###
