"""Initial migration

Revision ID: dfe40385cf2a
Revises: 
Create Date: 2019-05-21 09:50:41.175294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe40385cf2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phash', sa.String(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('gallery_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gallery_id'], ['gallery.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_to_image',
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_to_image')
    op.drop_table('image')
    op.drop_table('gallery')
    # ### end Alembic commands ###
